name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:             
    - uses: actions/checkout@v3
    - name: Build executables or extension modules from Python projects
      uses: Nuitka/Nuitka-Action@v0.6
      with:
        nuitka-version: main
        script-name: kopsrox.py
